version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch
    steps:
      - checkout
 
      - run:
          name: Install CxCLI Plugin
          command: |
            wget -O ~/cxcli.zip https://download.checkmarx.com/8.9.0/Plugins/CxConsolePlugin-8.90.0.zip
            unzip ~/cxcli.zip -d ~/cxcli
            chmod +x ~/cxcli/runCxConsole.sh

      - run:
          name: Execute CxSAST Scan
          command: |
            ~/cxcli/runCxConsole.sh Scan \
              -CxServer ec2-18-188-248-130.us-east-2.compute.amazonaws.com \
              -CxUser admin \
              -CxPassword Password!123 \
              -ProjectName 'CxServer\SP\Company\Users\dvwa' \
              -LocationType folder \
              -LocationPath ~/project \
              -ReportXML report-file.xml \
              -ReportPDF report-file.pdf \
              -Comment 'Launched from CircleCI' \
              -verbose

      - run: ls -lR ~/cxcli 

      # - store_artifacts:
      #   path: ~/cxcli
      #   destination: sast_results  

